Add support for terraform 0.14.x versions.
newcontext-oss/kitchen-terraform pull request #428
Opened 2020-12-03 16:36 UTC by brandocorp

Attempting to add support for the newly release Terraform 0.14.0.

2020-12-03 18:42 UTC, edwardbartholomew commented
Thank you very much for your contribution @brandocorp 

Would you mind adding a test for 0.14 in Travis as you have time? For reference, here is test for 0.13 which could mostly be duplicated I believe:
https://github.com/newcontext-oss/kitchen-terraform/blob/master/.travis.yml#L119-L150

I'm sorry @KevinBuchs, more work for the GitHub Actions refactor.

2020-12-03 19:41 UTC, brandocorp commented
@KevinBuchs, I sent a PR with a new test, but it is failing because the branch doesn't yet support 0.14.0 :grin: 

https://github.com/KevinBuchs/kitchen-terraform/pull/1/files

2020-12-07 20:16 UTC, wyardley commented
Is it possible to get this out soon?

2020-12-07 20:27 UTC, aaron-lane commented
@wyardley Thank you for your interest in the project! we're hoping to have it out tonight or tomorrow :crossed_fingers:

2020-12-07 20:41 UTC, wyardley commented
It looks like we can set `verify_version: false` to downgrade to a warning; may look at doing that. Historically, we haven't seen too many problems when jumping versions.

2020-12-07 21:10 UTC, aaron-lane commented
@wyardley yup, that's exactly why it's there! Given there aren't any logical gem changes in this branch, it seems like it should be safe to disable verification while we wrap this up.

2020-12-08 03:21 UTC, aaron-lane commented
@brandocorp might you please rebase your branch against master? :pleading_face:

2020-12-08 16:18 UTC, aaron-lane requested changes
Awesome possum 🤩 just need to update the change log date and we can release this

2020-12-08 16:18 UTC, aaron-lane commented on CHANGELOG.md
> +## [5.6.0] - 2020-12-04
Let's update this date and get this released!

```suggestion
## [5.6.0] - 2020-12-08
```

2020-12-08 16:19 UTC, aaron-lane approved these changes

2020-12-08 16:36 UTC, merged